# Use root/example as user/password credentials
version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: Datasets

  backend:
    build: ./backend
    image: "backend:latest"
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
